services:
  db:
    container_name: db
    image: postgres:13
    env_file:
      - ./PongWorld-Server/pongWorld/.env
    expose:
      - "5432"
    volumes:
      - ./PongWorld-Server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ft_transcendence
  
  backend:
    container_name: backend
    image: backend
    build: ./PongWorld-Server/pongWorld
    pull_policy: never
    env_file:
      - ./PongWorld-Server/pongWorld/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./PongWorld-Server/pongWorld
        target: /app 
    ports:
      - '8000:8000'
    networks:
      - ft_transcendence

  nginx:
    pull_policy: never
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports: 
      - 443:443
      - 80:80
    networks:
      - ft_transcendence
    depends_on:
      - backend
    volumes:
      - ./PongWorld-Client:/app/frontend
      - ./PongWorld-Server/pongWorld/media:/app/media

networks:
  ft_transcendence:
    driver: bridge